id: IB0A18D91
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:24:11+00:00'
last_modified: '2022-06-08T06:30:35.422174+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21997
  title: ཚད་མའི་དགོངས་དོན་བདེ་བླག་ཏུ་རྟོགས་པའི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AB4B:
      image_group_id: I4814
      title: ''
      total_pages: 198
      order: 1
      base_file: AB4B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
